import { Project } from "./project";
import { ProjectManager } from "./project-manager";
import { Task } from "./task";

const manager = new ProjectManager();
const project1 = new Project('All tasks');
const project2 = new Project('This day');
const project3 = new Project('Next 7 days');
const project4 = new Project('Football');
manager.addProject(project1);
manager.addProject(project2);
manager.addProject(project3);
manager.addProject(project4);
const task1 = new Task('Task 1', 'Description 1', '31/05/2024', 'high');
const task2 = new Task('Task 2', 'Description 2', '01/06/2024', 'low');
const task3 = new Task('Task 3', 'Description 3', '02/06/2024', 'high');
const task4 = new Task('Task 4', 'Description 4', '12/08/2042', 'high');
const task5 = new Task('Task 5', 'Description 5', '31/05/2024', 'middle');
const task6 = new Task('Task 6', 'Description 6', '31/05/2024', 'high');
const task7 = new Task('Task 7', 'Description 7', '01/12/2089', 'middle');
project1.addTask(task1);
project1.addTask(task2);
project1.addTask(task3);
project1.addTask(task4);
project1.addTask(task5);
project1.addTask(task6);
project1.addTask(task7);
project2.addTask(task1);
project2.addTask(task5);
project2.addTask(task6);
project3.addTask(task1);
project3.addTask(task5);
project3.addTask(task6);
project3.addTask(task2);
project3.addTask(task3);
project4.addTask(task7);
console.log(manager);