import { Project } from "./project";
import { ProjectManager } from "./project-manager";
import { Sorting } from "./sorting";
import { Task } from "./task";
import '../css/style.css';


const manager = new ProjectManager();
const project1 = new Project('All tasks');
const project2 = new Project('This day');
const project3 = new Project('Next 7 days');
const project4 = new Project('Football');
manager.addProject(project1);
manager.addProject(project2);
manager.addProject(project3);
manager.addProject(project4);
const task1 = new Task('Task 1', 'Description 1', new Date(2024, 5, 27), 'high');
const task2 = new Task('Task 2', 'Description 2', new Date(2024, 5, 27), 'low');
const task3 = new Task('Task 3', 'Description 3', new Date(2024, 6, 27), 'high');
const task4 = new Task('Task 4', 'Description 4', new Date(2025, 5, 27), 'high');
const task5 = new Task('Task 5', 'Description 5', new Date(2023, 6, 27), 'middle');
const task6 = new Task('Task 6', 'Description 6', new Date(2024, 5, 24), 'high');
const task7 = new Task('Task 7', 'Description 7', new Date(2021, 5, 27), 'middle');
task1.status = true;
task2.status = true;
task3.status = true;
project1.addTask(task1);
project1.addTask(task2);
project1.addTask(task3);
project1.addTask(task4);
project1.addTask(task5);
project1.addTask(task6);
project1.addTask(task7);
project2.addTask(task1);
project2.addTask(task5);
project2.addTask(task6);
project3.addTask(task1);
project3.addTask(task5);
project3.addTask(task6);
project3.addTask(task2);
project3.addTask(task3);
project4.addTask(task7);
const sorter = new Sorting();
sorter.taskSort(project1.tasks);
console.log(manager);
